CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: wsoc11
  ROOT: data/
  TEST_SET: 'list/wsoc11/test.lst'
  TRAIN_SET: 'list/wsoc11/train.lst'
  NUM_CLASSES: 11
MODEL:
  NAME: pidnet_l
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/cityscapes/PIDNet_L_Cityscapes_val.pt"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 1280
  - 960
  BASE_SIZE: 16
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: false
  BEGIN_EPOCH: 0
  END_EPOCH: 400
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.006
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: true
  MULTI_SCALE: true
  MODEL_FILE: "pretrained_models/cityscapes/PIDNet_S_Cityscapes_test.pt"
  OUTPUT_INDEX: 1
